Global connectors
blindnet-io/storage-connector-java pull request #4
Opened 2022-11-10 02:12 UTC by TheKinrar

Adds support for global connectors, together with https://github.com/blindnet-io/data-access-component/pull/3.

Many changes to the library, but API compatibility was preserved (no changes to the example/demo module).

2022-11-11 11:30 UTC, m4rk055 requested changes

2022-11-11 11:30 UTC, m4rk055 commented on core/src/main/java/io/blindnet/storageconnector/impl/DataAccessClientImpl.java
> +            if(!System.getenv().containsKey("DISABLE_RETRY_BACKOFF")) {
Settings like this or [this](https://github.com/blindnet-io/storage-connector-java/pull/4/files#diff-0f8c0adab2d4ee304e31fc42994630eda6acc1fc80c2ab14d89fbdd2bbdc0a2cR18) should rather be passed to the `StorageConnector` constructor. It improves transparency.

2022-11-11 11:30 UTC, m4rk055 commented on core/src/main/java/io/blindnet/storageconnector/impl/DataAccessClientImpl.java
> +    private ExecutorService executorService = Executors.newCachedThreadPool();
Make it easier to set the the Executor when instantiating the StorageConnector.

2022-11-14 10:02 UTC, TheKinrar commented on core/src/main/java/io/blindnet/storageconnector/impl/DataAccessClientImpl.java
> +            if(!System.getenv().containsKey("DISABLE_RETRY_BACKOFF")) {
The endpoint is already customizable with `CustomStorageConnector.create(String token, String endpoint)`. As for the disable retry backoff, I didn't really want to advertise this as it's more of a debug feature for development. There's no point in using this in production.

2022-11-14 10:30 UTC, m4rk055 approved these changes

2022-11-29 17:44 UTC, merged